CREATE TABLE availability (
    availability_id int(11) not null AUTO_INCREMENT PRIMARY KEY,
    availability_vehicle_id int(11) not null,
    CONSTRAINT fk_vehicle FOREIGN KEY (availability_vehicle_id) 
        REFERENCES vehicle(vehicle_id)
        ON DELETE CASCADE  
        ON UPDATE CASCADE,
    availability_monday tinyint(1) not null,
    availability_monday_start_time time not null,
    availability_monday_end_time time not null,
    availability_tuesday tinyint(1) not null,
    availability_tuesday_start_time time not null,
    availability_tuesday_end_time time not null,
    availability_wednesday tinyint(1) not null,
    availability_wednesday_start_time time not null,
    availability_wednesday_end_time time not null,
    availability_thursday tinyint(1) not null,
    availability_thursday_start_time time not null,
    availability_thursday_end_time time not null,
    availability_friday tinyint(1) not null,
    availability_friday_start_time time not null,
    availability_friday_end_time time not null,
    availability_saturday tinyint(1) not null,
    availability_saturday_start_time time not null,
    availability_saturday_end_time time not null,
    availability_sunday tinyint(1) not null,
    availability_sunday_start_time time not null,
    availability_sunday_end_time time not null,
    availability_january tinyint(1) not null,
    availability_february tinyint(1) not null,
    availability_march tinyint(1) not null,
    availability_april tinyint(1) not null,
    availability_may tinyint(1) not null,
    availability_june tinyint(1) not null,
    availability_july tinyint(1) not null,
    availability_august tinyint(1) not null,
    availability_september tinyint(1) not null,
    availability_october tinyint(1) not null,
    availability_november tinyint(1) not null,
    availability_december tinyint(1) not null
);